### PR TITLE
updated to new CGRtools

### PR DESCRIPTION
**Pull request by stsouko**
fixes.
but I found problem with new sssr algorithm implemented in CGRtools.
I need some time for fixing it.

### CODE REVIEW

**Comment by stsouko** [comment]
жизнь боль. старый алгоритм совка был быстр, но пролетал порой.
новый протелает крайне редко, но зараза имеет сложность N^3 (N - число атомов) а не ~N+M как старый (M - число связей)
короче говоря все ой как плохо если атомов больше пары сотен

**Comment by DrrDom** [comment]
Thank you! So we will wait for a final version.
I would like to point out that MetalComplex features were not added to pmapper master and may cause issues. I also noticed HalogenDonor/Acceptor, but these features are not supported by pmapper. You may keep these three features if they will not cause issues or please remove them from the final version.

**Comment by stsouko** [comment]
now sssr algorithm fixed in CGRtools.
also updated aromatic rings detection (new in CGRtools).
molecule class monkey patching changed to new api of file parsers.

**Comment by stsouko** [comment]
> Thank you! So we will wait for a final version.
> I would like to point out that MetalComplex features were not added to pmapper master and may cause issues. I also noticed HalogenDonor/Acceptor, but these features are not supported by pmapper. You may keep these three features if they will not cause issues or please remove them from the final version.

no. these types of interactions disabled.

**Pull request merged**
